version: 1
sources:
  # === 国际顶级 ===
  - name: codeforces
    enabled: true
    type: codeforces
    url: https://codeforces.com/api/contest.list?gym=false
  - name: atcoder
    enabled: true
    type: atcoder
    url: https://kenkoooo.com/atcoder/resources/contests.json
  - name: drivendata
    enabled: true
    type: drivendata
    url: https://www.drivendata.org/competitions/
  - name: kaggle
    enabled: true
    type: kaggle
    url: https://www.kaggle.com/competitions

  # === 国内官方高质量 (新增) ===
  - name: CUMCM 官网公告
    enabled: true
    type: cumcm
    url: https://www.mcm.edu.cn/html_cn/block/20ead73cbcf5a1c24b91947f98d7aac2.html
    category_fixed: 数学建模
    detail: true
    detail_limit: 20
    detail_selectors:
      content: ".content, .detail"
  - name: COMAP MCM/ICM
    enabled: true
    type: comap
    url: https://www.comap.com/contests/mcm-icm
    category_fixed: 数学建模
    detail: true
  - name: NSCSCC 系统能力大赛
    enabled: true
    type: nscscc
    url: https://www.nscscc.com/
    category_fixed: 编程
    detail: true
    detail_limit: 20
    detail_selectors:
      content: ".news-detail, .content"
  - name: 蓝桥杯
    enabled: true
    type: lanqiao
    url: https://dasai.lanqiao.cn/
    category_fixed: 编程
    detail: true
    detail_limit: 20
  - name: 阿里云天池
    enabled: true
    type: tianchi
    url: https://tianchi.aliyun.com/competition/
    category_fixed: AI数据
    detail: true
    detail_limit: 20
  - name: 挑战杯
    enabled: true
    type: challengecup
    url: https://www.tiaozhanbei.net/tzb/notice
    category_fixed: 创新创业
    detail: true
    detail_limit: 20
    detail_selectors:
      content: ".notice-content, .article"

  # === 聚合平台 (Saikr/52) ===
  - name: saikr_mcm
    enabled: true
    type: saikr
    url: https://www.saikr.com/vs/mcm
    category_fixed: 数学建模
    pages: 8
  - name: saikr_acm
    enabled: true
    type: saikr
    url: https://www.saikr.com/vs/acm/0/0
    category_fixed: 编程
    pages: 8
  - name: saikr_ai
    enabled: true
    type: saikr
    url: https://www.saikr.com/vs/ai/6/0?univs=0
    category_fixed: AI数据
    pages: 8
  - name: saikr_bigdata
    enabled: true
    type: saikr
    url: https://www.saikr.com/vs/big_data/1/1
    category_fixed: AI数据
    pages: 8
  - name: saikr_startup
    enabled: true
    type: saikr
    url: https://www.saikr.com/vs/chuangye/5/0
    category_fixed: 创新创业
    pages: 8
  # 52jingsai sources
  - name: 52jingsai_tech
    enabled: true
    type: 52jingsai
    url: https://m.52jingsai.com/list-15-1.html
    category_fixed: AI数据
    pages: 6
  - name: 52jingsai_innovation
    enabled: true
    type: 52jingsai
    url: https://m.52jingsai.com/list-14-1.html
    category_fixed: AI数据
    pages: 6
  - name: 52jingsai_startup
    enabled: true
    type: 52jingsai
    url: https://m.52jingsai.com/list-3-1.html
    category_fixed: 创新创业
    pages: 6
