version: 1
sources:
  - name: codeforces
    enabled: true
    type: codeforces
    url: https://codeforces.com/api/contest.list?gym=false
  - name: atcoder
    enabled: true
    type: atcoder
    url: https://kenkoooo.com/atcoder/resources/contests.json
  - name: drivendata
    enabled: true
    type: drivendata
    url: https://www.drivendata.org/competitions/
  - name: cumcm
    enabled: true
    type: cumcm
    url: https://www.mcm.edu.cn/
  - name: challengecup
    enabled: true
    type: challengecup
    url: https://2025.tiaozhanbei.net/
  - name: kaggle
    enabled: true
    type: kaggle
    url: https://www.kaggle.com/competitions
  - name: saikr
    enabled: true
    type: saikr
    url: https://www.saikr.com/vs?set_web=1
    pages: 3
  - name: 52jingsai_ai
    enabled: true
    type: 52jingsai
    url: https://m.52jingsai.com/list-17-10.html
    category_fixed: AI数据
    pages: 2
  - name: 52jingsai_math
    enabled: true
    type: 52jingsai
    url: https://m.52jingsai.com/list-309-5.html
    category_fixed: 数学建模
    pages: 2
  - name: 52jingsai_startup
    enabled: true
    type: 52jingsai
    url: https://m.52jingsai.com/list-3-1.html
    category_fixed: 创新创业
    pages: 2
  - name: 52jingsai_code
    enabled: true
    type: 52jingsai
    url: https://m.52jingsai.com/list-14-5.html
    category_fixed: 编程
    pages: 2
