version: 1
sources:
  - name: codeforces
    enabled: true
    type: codeforces
    url: https://codeforces.com/api/contest.list?gym=false
  - name: atcoder
    enabled: true
    type: atcoder
    url: https://kenkoooo.com/atcoder/resources/contests.json
  - name: drivendata
    enabled: true
    type: drivendata
    url: https://www.drivendata.org/competitions/
  - name: cumcm
    enabled: true
    type: cumcm
    url: https://www.mcm.edu.cn/
  - name: challengecup
    enabled: true
    type: challengecup
    url: https://2025.tiaozhanbei.net/
  - name: 52jingsai
    enabled: true
    type: 52jingsai
    url: https://www.52jingsai.com/
  - name: kaggle
    enabled: true
    type: kaggle
    url: https://www.kaggle.com/competitions
  - name: saikr
    enabled: true
    type: saikr
    url: https://m.saikr.com/vs
