version: 1
sources:
  - name: codeforces
    enabled: true
    type: codeforces
    url: https://codeforces.com/api/contest.list?gym=false
  - name: atcoder
    enabled: true
    type: atcoder
    url: https://kenkoooo.com/atcoder/resources/contests.json
  - name: drivendata
    enabled: true
    type: drivendata
    url: https://www.drivendata.org/competitions/
  - name: cumcm
    enabled: true
    type: cumcm
    url: https://www.mcm.edu.cn/
  - name: challengecup
    enabled: true
    type: challengecup
    url: https://2025.tiaozhanbei.net/
  - name: kaggle
    enabled: true
    type: kaggle
    url: https://www.kaggle.com/competitions
  # Saikr sources with pagination
  - name: saikr_mcm
    enabled: true
    type: saikr
    url: https://www.saikr.com/vs/mcm
    category_fixed: 数学建模
    pages: 8
  - name: saikr_acm
    enabled: true
    type: saikr
    url: https://www.saikr.com/vs/acm/0/0
    category_fixed: 编程
    pages: 8
  - name: saikr_ai
    enabled: true
    type: saikr
    url: https://www.saikr.com/vs/ai/6/0?univs=0
    category_fixed: AI数据
    pages: 8
  - name: saikr_bigdata
    enabled: true
    type: saikr
    url: https://www.saikr.com/vs/big_data/1/1
    category_fixed: AI数据
    pages: 8
  - name: saikr_startup
    enabled: true
    type: saikr
    url: https://www.saikr.com/vs/chuangye/5/0
    category_fixed: 创新创业
    pages: 8
  # 52jingsai sources
  - name: 52jingsai_tech
    enabled: true
    type: 52jingsai
    url: https://m.52jingsai.com/list-15-1.html
    category_fixed: AI数据
    pages: 6
  - name: 52jingsai_innovation
    enabled: true
    type: 52jingsai
    url: https://m.52jingsai.com/list-14-1.html
    category_fixed: AI数据
    pages: 6
  - name: 52jingsai_startup
    enabled: true
    type: 52jingsai
    url: https://m.52jingsai.com/list-3-1.html
    category_fixed: 创新创业
    pages: 6
